{ inputs, ... }:
{
  flake.modules.nixos.graphical = {
    imports = [ inputs.hyprland.nixosModules.default ];

    programs.hyprland = {
      enable = true;
      withUWSM = true;
    };
  };

  flake.modules.homeManager.graphical = { pkgs, ... }: {
    wayland.windowManager.hyprland = {
      enable = true;
      package = null;
      portalPackage = null;

      settings.xwayland.force_zero_scaling = true;

      extraConfig = ''
        autogenerated = 0

        source = ~/.config/hypr/hyprland/catppuccin.conf
        source = ~/.config/hypr/hyprland/keywords.conf
        source = ~/.config/hypr/hyprland/autostart.conf
        source = ~/.config/hypr/hyprland/laptop.conf
        source = ~/.config/hypr/hyprland/envvars.conf
        source = ~/.config/hypr/hyprland/layout.conf
        source = ~/.config/hypr/hyprland/windowrules.conf
        source = ~/.config/hypr/hyprland/workspaces.conf
        source = ~/.config/hypr/hyprland/input.conf
        source = ~/.config/hypr/hyprland/keybindings.conf
        source = ~/.config/hypr/hyprland/plugins.conf
        source = ~/.config/hypr/hyprland/autolaunch.conf
      '';

      plugins = [
        inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprexpo
        inputs.hyprland-plugins.packages.${pkgs.stdenv.hostPlatform.system}.hyprbars
      ];
    };
  };
}
